### PR TITLE
Upgrade libraries to support Java 21

### PR DESCRIPTION
**Pull request by RoqueIT**
Upgrade libraries to support Java 21

### CODE REVIEW

**Comment by vincent-fuchs** [comment]
available in 4.0.0 , please give it a try !

**Comment by guerrillalg** [comment]
Apparently, this broke the compatibility with Java17 and others pre 21 versions. Now this jar file is only usable with java 21 and up.

**Comment by vincent-fuchs** [comment]
yes, I am not surprised. 

You can stay on v3.x , the features are the same, at least for now

**Comment by guerrillalg** [comment]
Thanks for cherry-picking it! 
Do you have some plans on how to support different java versions? Like 3.* for java 11-20 and 4.* for java 21+ ? Or maybe you would include java version into the classifier of the artifact, so that we can explicitly choose which one to use?

**Comment by vincent-fuchs** [comment]
@guerrillalg : it is now available in https://github.com/societe-generale/arch-unit-maven-plugin/releases/tag/archUnit_maven_plugin_3.0.1 

there's no plan for extra support for 3.x . only the strict minimum, but anyway, we don't expect major new features, so it should be enough.

**Pull request merged**
