### PR TITLE
reviewing tests for ArchUnitMojo

### PR DESCRIPTION
**Pull request by vincent-fuchs**
## Summary

After previous refactoring, I noticed code coverage had dropped, mainly on ArchUnitMojo. 

--> Reviewing the tests to have effective functional test coverage

## Checklist:

- [X] I've added tests for my code.
- [ ] Documentation has been updated accordingly to this PR

### CODE REVIEW

**Comment by vincent-fuchs** [comment]
@arpitgarg9168 , we need to discuss the unit tests for this class and review them. Coverage has increased a lot with simple changes above, but tests are not actually testing well the logic.

**Comment by FanJups** [comment]
@vincent-fuchs    coverage increased from 70 % to 87%. Great but why wasn't the case before ? The program was supposed to get the value from the property named " projectPath " and used it. What is the added value of defining a default project path other than increasing test coverage ? Is it a simple variable initialization to avoid NullPointerException ?

**Comment by arpitgarg9168** [comment]
> @vincent-fuchs coverage increased from 70 % to 87%. Great but why wasn't the case before ? The program was supposed to get the value from the property named " projectPath " and used it. What is the added value of defining a default project path other than increasing test coverage ? Is it a simple variable initialization to avoid NullPointerException ?

**Comment by vincent-fuchs** [comment]
> @vincent-fuchs coverage increased from 70 % to 87%. Great but why wasn't the case before ? The program was supposed to get the value from the property named " projectPath " and used it. What is the added value of defining a default project path other than increasing test coverage ? Is it a simple variable initialization to avoid NullPointerException ?

default value indeed enables to avoid the NPE in the test, which was my original goal when I started working on this. But it also simplifies the config : users don't need to provide a value if the default value is good for them. 

I feel we can do better in terms of tests because we have coverage, but no proper assertions in the tests : 
- I don't understand _shouldFailAsTestClassPathElementsAreMocked_
 - we are not asserting separately the execution of preConfiguredRules and configurableRules , so any regression there may not be caught unit tests

I'll discuss with @arpitgarg9168  and try to improve this

**Comment by vincent-fuchs** [comment]
@arpitgarg9168 , please have a look at ;y last commit, I feel it's much better now. Don't hesitate to make/suggest changes. But if you're OK, let's merge and make a release

**Pull request merged**
